// Copyright (2024) Beijing Volcano Engine Technology Ltd.

// Licensed under the Apache License, Version 2.0 (the "License"); 
// you may not use this file except in compliance with the License. 
// You may obtain a copy of the License at 

//     http://www.apache.org/licenses/LICENSE-2.0 

// Unless required by applicable law or agreed to in writing, software 
// distributed under the License is distributed on an "AS IS" BASIS, 
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
// See the License for the specific language governing permissions and 
// limitations under the License. 

export class Constants {
  static readonly TAG = "bef_effect_ai";
  static readonly X_COMPONENT_BORDER_WIDTH = 0.5;
  static readonly X_COMPONENT_SURFACE_HEIGHT = 720;
  static readonly X_COMPONENT_SURFACE_WIDTH = 1280;

  static readonly ZERO_PERCENT: string = '0%';
  static readonly TEN_PERCENT: string = '10%';
  static readonly THIRTY_PERCENT: string = '30%';
  static readonly EIGHTY_PERCENT: string = '80%';
  static readonly FULL_PERCENT: string = '100%';
}